# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: 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
        # Comment to post on an individual's first issue
        issue-message: Good luck solving this one:)
        # Comment to post on an individual's first pull request
        pr-message: Well done on your first PR. Enjoy your day!
        

